### ISSUE TITLE
`Apple ID`or `Bundle ID` for use in appID parameter 

### ISSUE THREAD

**Issue by dk-WZFinTech** [dpa99c/cordova-launch-review#12]
**I'm submitting a ...**  (check one with "x"):
- [ ] bug report
- [ ] feature request
- [x] documentation issue

# Documentation issue

In Documentation you wrote:

`{string} appID [...] If not specified, the plugin will use the app ID for the app in which the plugin is contained`

**But for iOS is not clear if this is a `Apple ID`or `Bundle ID`.**

I assume that it is `Bundle ID` cause this is only one that we can set in Xcode on _General > Bundle Identifier_ 

In the same time as parameter in `launch()` `Advanced usage` is used `Apple ID` - when I try to use `Bundle Id` I get an error appears: `App not found`.
 
**Can you clarify this issue in Documentation: which one (`Apple ID`or `Bundle ID`) should be used?**

_BTW_ Is `rating`mrthod also use `Bundle ID` as default?

**Comment by dpa99c** [comment]
[As documented](https://github.com/dpa99c/cordova-launch-review#launch):

> On iOS this is the Apple ID of the app. For example, for Google Maps: `585027354`

The Apple ID is the unique ID that Apple assigns to an app in the App Store.

So, for example Google Maps on the App Store is: https://itunes.apple.com/gb/app/google-maps-gps-navigation/id585027354?mt=8

where `585027354` is its Apple ID.

The Apple ID is not available offline inside of the app bundle, since it is assigned by Apple in the App Store.
Therefore, if you call `launch()` with specifying the Apple ID, it will make a lookup request to Apple, passing in the bundle ID from the app package and receiving the Apple ID in the response.

If still in doubt: [look at the code](https://github.com/dpa99c/cordova-launch-review/blob/master/src/ios/LaunchReview.m#L168)

> BTW Is ratingmrthod also use Bundle ID as default?

[As documented](https://github.com/dpa99c/cordova-launch-review#rating):

> On iOS 10.3 and above, invokes the [native in-app rating dialog](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview) which allows a user to rate your app without needing to open the App Store.

Since it calls a native API method, no ID needs to be specified: the iOS API does not require it.

**Comment by dk-WZFinTech** [comment]
Thank you for clarify this issue. I need to say that I love your work in this package. 

In our Ionic base APP for some other functionality we also use `Apple ID` which is global stored in env files and as I wrote I was not sure if it is used instead of `Bundle ID`.

Now everything is clear.

But maybe you can consider to add this note to documentation:

> Therefore, if you call launch() with specifying the Apple ID, it will make a lookup request to Apple, passing in the bundle ID from the app package and receiving the Apple ID in the response.

What do you think?

Out of topic> I found [that discussion](https://stackoverflow.com/questions/45057452/why-the-skstorereviewcontroller-does-not-let-me-submit-a-review) about disabled `Submit` button on Rating Pop-up (I did know this is active only on AppStore product, not on TestFlight)
