### ISSUE TITLE
App rating dialog takes a bit of time to appear

### ISSUE THREAD

**Issue by sneko** [dpa99c/cordova-launch-review#15]
**I'm submitting a ...**  (check one with "x"):
- [X] bug report
- [ ] feature request
- [ ] documentation issue

# Bug report

**Current behavior:**

When I'm using the plugin feature of showing the app rating dialog, the first time it takes a few seconds to appear. And the following attempts are almost instantaneous.

**Expected behavior:**

Being almost instantaneous from the first attempt.

Note: I'm connected to Wifi so the problem should not be something about downloading remote information.

**Steps to reproduce:**

**Environment information**

I'm using an iPhone 6 with iOS 12.2

Thank you @dpa99c , you've done a great job :)

**Comment by dpa99c** [comment]
This plugin's app rating dialog call is just a [very thin wrapper](https://github.com/dpa99c/cordova-launch-review/blob/master/src/ios/LaunchReview.m#L77) around the native [SKStoreReviewController requestReview](https://developer.apple.com/documentation/storekit/skstorereviewcontroller/2851536-requestreview?language=objc) method which it calls to invoke the ratings dialog. The delay is caused by the iOS StoreKit framework while it carries out async comms with the Apple Storekit servers. 

Therefore there's nothing that can be done by this plugin (or any native app code) to reduce that delay.
