### ISSUE TITLE
Ionic 5 using native api capacitor

### ISSUE THREAD

**Issue by josecarvalhoSigned** [dpa99c/cordova-launch-review#27]
Using the exact code like is explained on Ionic documentation for native apps the rating screen in app is not displaying. The function isRatingSupported() is returning true. Any help??

https://ionicframework.com/docs/native/launch-review

**Comment by dpa99c** [comment]
The Ionic Native Typescript wrapper is created/maintained by Ionic so if there's an issue with it please raise it against Ionic Native.
Also note this is a Cordova plugin so Capacitor is not officially supported.
Please read [the documentation](https://github.com/dpa99c/cordova-launch-review) carefully as to the behaviour of both mobile platforms as to when the native dialogs will be shown.
Finally please build and run the [example project](https://github.com/dpa99c/cordova-launch-review-example) which demonstrates usage of this plugin and expected behaviour.
AFAIK there is no issue with this plugin as to when the native raing dialogs is displayed; this is determined by the OS on both mobile platforms.
